apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/deviant101/Monitoring-Stack-ArgoCD.git
    targetRevision: main
    path: pulse/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
